defaults:
  - hydra: default
  - dataset: null
  - task: null
  - task/context_aggregator: null
  - task/predictor: null
  - _self_

seed: 27
save_dir: null

logger:
  _target_: lightning.pytorch.loggers.WandbLogger
  entity: "thomas-jiralerspong"
  project: "Prequential-ICL"
  name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
  save_dir: ${save_dir}
  offline: False
  tags: null


name: ${task_name}_${dataset.name}
